version: '2'
services:
  logicaldoc:
    build: ../logicaldoc-ee762-mysql
    container_name: logicaldoc
    image: logicaldoc/logicaldoc-ee762-mysql
    ports:
        - 8080:8080
    volumes:
        - mysqldata:/var/lib/mysql
        - confdata:/opt/logicaldoc/conf  
        - repodata:/opt/logicaldoc/repository
volumes:
    mysqldata:
        external: true
    confdata:
        external: true
    repodata:
        external: true








